light_bubble_color_1:
  default: "#ddf9d3"
  type: string
  description: Chat bubble color for you, used in the the light scheme.
light_bubble_color_2:
  default: "#FFFFFF"
  type: string
  description: Chat bubble color for others, used in the light scheme.
dark_bubble_color_1:
  default: "#215046"
  type: string
  description: Chat bubble color for you, used in the the dark scheme.
dark_bubble_color_2:
  default: "#000000"
  type: string
  description: Chat bubble color for others, used in the dark scheme.
background_color:
  default: "#fff8eb"
  type: string
  description: Background color for the chat window.
background_pattern:
  default: ""
  type: upload
  description: Background pattern for the chat window, works best with SVGs. If you want to use an image instead, make sure it's optimised for mobile device viewport.
